{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-deblur
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - pandas {{ pandas }}
    - numpy
    - deblur >=1.0.4
    - click >=8.1
    - vsearch
    - qiime2 {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2templates >={{ q2templates }}
    - q2-types >={{ q2_types }}
    - nose

  imports:
    - q2_deblur
    - qiime2.plugins.deblur

  # uncomment and remove run_test.sh when 1.1.2 lands (which should include:
  # https://github.com/biocore/deblur/pull/216)
  # commands:
  #   - pytest --pyargs deblur
  additional-tests: py.test --pyargs q2_deblur

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
