{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-deblur
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - pandas
    - numpy
    - deblur >=1.0.4
    # There are issues with 2.8.2, and no OS X builds exist after 2.7.0
    - vsearch <=2.7.0
    - qiime2 {{ release }}.*
    - q2templates {{ release }}.*
    - q2-types {{ release }}.*

test:
  imports:
    - q2_deblur
    - qiime2.plugins.deblur

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
